### ISSUE TITLE
TODO: make this site look like static2.ten7.com (same as tractorbeam.ten7.com)

### ISSUE THREAD

**Issue by joshcesana** [ten7/computingforcovid.ten7.com#2]
- per @ivanstegic, this site is to look like static2.ten7.com (originally, tractorbeam.ten7.com)

**Comment by joshcesana** [comment]
https://github.com/ten7/computingforcovid.ten7.com/pull/3

**Comment by ivanstegic** [comment]
@joshcesana your PR brings in the content from Tractorbeam. This site needs to retain its content and the navigation needs to be updated to reflect the content on the actual Computing for COVID site.

**Comment by joshcesana** [comment]
@ivanstegic Fixed: https://github.com/ten7/computingforcovid.ten7.com/pull/4
